CREATE TABLE drivers (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    first_name TEXT NOT NULL,
    last_name TEXT NOT NULL,
    mobile_number TEXT NOT NULL,
    password TEXT NOT NULL,
    email TEXT,
    active BOOLEAN DEFAULT FALSE NOT NULL,
    paused BOOLEAN DEFAULT FALSE NOT NULL,
    on_trip BOOLEAN DEFAULT FALSE NOT NULL,
    current_trip INTEGER,
    date_created TIMESTAMP NOT NULL
);