CREATE TABLE drivers (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    first_name TEXT NOT NULL,
    last_name TEXT NOT NULL,
    mobile_number TEXT NOT NULL,
    email TEXT NOT NULL,
    password TEXT NOT NULL,
    on_trip BOOLEAN DEFAULT FALSE NOT NULL,
    last_known_lat TEXT DEFAULT "" NOT NULL,
    last_known_lng TEXT DEFAULT "" NOT NULL,
    last_zip_code TEXT DEFAULT "" NOT NULL,
    active BOOLEAN DEFAULT FALSE NOT NULL,
    active_start_time TIMESTAMP DEFAULT FALSE NOT NULL,
    paused BOOLEAN DEFAULT FALSE NOT NULL,
    last_paused_time TIMESTAMP DEFAULT FALSE NOT NULL,
    signed_off_time TIMESTAMP NOT NULL,
    date_created TIMESTAMP NOT NULL
);