CREATE TABLE passengers (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    first_name TEXT NOT NULL,
    last_name TEXT NOT NULL,
    mobile_number TEXT NOT NULL,
    password TEXT NOT NULL,
    email TEXT NOT NULL,
    home_address TEXT,
    work_address TEXT,
    trip_redemption BIGINT DEFAULT 0 NOT NULL,
    member BOOLEAN DEFAULT FALSE NOT NULL,
    date_created TIMESTAMP
);