CREATE TABLE passengers (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    first_name TEXT NOT NULL,
    last_name TEXT NOT NULL,
    mobile_number TEXT NOT NULL,
    password TEXT NOT NULL,
    email TEXT NOT NULL,
    pro_member BOOLEAN DEFAULT FALSE NOT NULL,
    date_created TIMESTAMP NOT NULL
);