CREATE TABLE trips (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    pick_up_address TEXT NOT NULL,
    drop_off_address TEXT NOT NULL,
    number_of_stops BIGINT DEFAULT 1 NOT NULL,
    stops TEXT [] DEFAULT '{}' NOT NULL, 
    miles DECIMAL DEFAULT 0.00 NOT NULL,
    price DECIMAL DEFAULT 0.00 NOT NULL,
    scheduled BOOLEAN DEFAULT FALSE NOT NUll,
    scheduled_time TEXT,
    time_driver_accepted TIMESTAMP,
    time_passenger_got_in TIMESTAMP,
    driver_id BIGINT NOT NULL,
    passenger_id BIGINT NOT NULL,
    complete BOOLEAN DEFAULT FALSE NOT NULL,
    time_trip_completed TIMESTAMP,
    time_requested TIMESTAMP,
    date_created TIMESTAMP NOT NULL
);