CREATE TABLE trips (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    time_trip_finished TIMESTAMP,
    pick_up_address TEXT NOT NULL,
    drop_off_address TEXT NOT NULL,
    number_of_stops INTEGER DEFAULT 1 NOT NULL,
    stops TEXT [] DEFAULT '{}' NOT NULL, 
    miles DECIMAL DEFAULT 0.00 NOT NULL,
    price DECIMAL DEFAULT 0.00 NOT NULL,
    scheduled BOOLEAN DEFAULT FALSE NOT NUll,
    scheduled_time TEXT,
    driver_id INTEGER NOT NULL,
    passenger_id INTEGER NOT NULL,
    date_created TIMESTAMP NOT NULL
);