CREATE TABLE members (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    days_work TEXT [] DEFAULT '{}' NOT NULL,
    upcoming_days_off TEXT [] DEFAULT '{}' NOT NULL,
    work_address TEXT NOT NULL,
    passenger_id BIGINT REFERENCES passengers(id) ON DELETE CASCADE NOT NULL
);